version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build_and_test:
    docker: 
      - image: cimg/node:12.22.0
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test -- --coverage
          name: Run tests
      - run:
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/clover.xml
          name: Codacy coverage
workflows:
  on_commit:
    jobs:
      - build_and_test
